### ISSUE TITLE
Managing Additional Asset Types

### ISSUE THREAD

**Issue by MattFranklin-Rapid** [RAPID-Platform-Projects/Rapid-Docs#106]
## Description
Jono's existing training

## Training Covers
- Creating a subtype table
- Creating new columns on a subtype table
- Customising the sidebar
Links to:
- Adding new columns to a table
- Building the Create and Details layout for a table
- Creating a new view (to only see the new asset type in the main assets table)

**Comment by jinferno** [comment]
Does the "training covers" section fit okay with the other training articles?
