### ISSUE TITLE
Replace screenshots of "Support Bot" to reflect corrected spelling

### ISSUE THREAD

**Issue by decept1kon** [RAPID-Platform-Projects/Rapid-Docs#182]
### Contact Details

josh@rapidplatform.com

### What is the issue?

[Screenshots here should be replaced](https://docs.rapidplatform.com/changelog/2024/03/26/2024-03-26-1.38%20-%20Rapid%20Platform/1.38%20-%20Rapid%20Platform)

The 1.38.0 changelog screenshots need to be updated to match the support bot's corrected spelling.

### What browsers are you seeing the problem on?

Firefox

**Comment by MattFranklin-Rapid** [comment]
All images in the permanent docs should be updated, blog post can be left as an archive of our mistakes
