### ISSUE TITLE
User Manual : Explorer : Attachments Component

### ISSUE THREAD

**Issue by MattFranklin-Rapid** [RAPID-Platform-Projects/Rapid-Docs#78]
Can click the attachments pane to start the upload file action

Can drag a file onto the attachments component to upload it
Can see files are uploading
Creates a new folder on the current item when adding a file if one doesn't exist
Uploaded files create an attachment record (card)
Can open an attachment record
Can download an attachment record
Can remove an attachment record, which deletes the file
Attachments are uploaded to an attachments folder in the items folder

**Comment by jinferno** [comment]
# Completed:
- Can click the attachments pane to start the upload file action
- Can drag a file onto the attachments component to upload it
- Can see files are uploading
- Creates a new folder on the current item when adding a file if one doesn't exist
- Uploaded files create an attachment record (card)
- Can open an attachment record
- Can download an attachment record
- Can remove an attachment record, which deletes the file
- Attachments are uploaded to an attachments folder in the items folder
