### ISSUE TITLE
User Manual : Explorer : Item History

### ISSUE THREAD

**Issue by MattFranklin-Rapid** [RAPID-Platform-Projects/Rapid-Docs#80]
Can view the list of versions of an item
Selecting a past version fetches the item as of that time
Past versions of items are indicated in the UI
Can revert the current version of the item

**Comment by jinferno** [comment]
### Completed:
- Explained how to view past versions of an item
- Explained that selecting past versions fetches the item as of that time.
- Took screenshots to explain UI changes that indicate past versions
- Explains how to revert changes
