### ISSUE TITLE
User Manual : Explorer : Data Table

### ISSUE THREAD

**Issue by MattFranklin-Rapid** [RAPID-Platform-Projects/Rapid-Docs#81]
Probably at least 2 articles:

Can see a list of items in columns
Can create a new item
Can create new sub-types of items
Can not create base types if marked in designer
Can search for items in the list
Can inline refresh the data table
Items display their entity type icon
Item icons are clickable and open the item page
Title fields display as clickable links that open the item page
Can double click a row to open the item
Each field displays correctly for its type
Can see date fields as dates when enabled in the view
Can see date fields as moment when enabled in the view
Scrolling to the bottom of a list of items triggers infinite scroll
Can see embedded files fields as progress bars
On hover, embedded file fields present a list of file slots in their definition
Can see if an embedded file slot is filled
Can open the file from an embedded file slot when filled

Can download a CSV version of the current list and view

**Comment by jinferno** [comment]
@MattFranklin-Rapid Can I get more context on these two pieces of content and what they mean?

- Each field displays correctly for its type
- Scrolling to the bottom of a list of items triggers infinite scroll
