### ISSUE TITLE
User Manual : Explorer : PowerBI Item Level

### ISSUE THREAD

**Issue by MattFranklin-Rapid** [RAPID-Platform-Projects/Rapid-Docs#88]
Reports a fetched and viewable from the workspace based on the selected report field
Can replace the report with another
If there is no report field value, can select an existing report to use
If there is no report field value, can upload a new report to use
With edit mode enabled, can edit the report
With item level filtering enabled, reports on an item context have a filter added of {listname}:{id}

**Comment by jinferno** [comment]
@MattFranklin-Rapid Is this suitable for User Manual? It feels closer to Keyper, as most of these items are about building out a site by adding reporting functionality to it.
